import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 */

group = "com.code.catalyst"
version = "1.0"
description = "Backend Data Aggregator"
java.sourceCompatibility = JavaVersion.VERSION_21


plugins {
    kotlin("jvm") version "2.1.0"
    kotlin("plugin.serialization") version "2.1.0"
    application
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo1.maven.org/maven2/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {

    val exposedVersion = "1.0.0-beta-4"
    val ktorVersion = "3.1.2"


    implementation("io.ktor:ktor-client-core-jvm:${ktorVersion}")
    implementation("io.ktor:ktor-client-cio:${ktorVersion}")
    implementation("io.ktor:ktor-server-core-jvm:${ktorVersion}")
    implementation("io.ktor:ktor-server-call-id:${ktorVersion}")
    implementation("io.ktor:ktor-server-call-logging:${ktorVersion}")
    implementation("io.ktor:ktor-server-netty-jvm:${ktorVersion}")
    implementation("io.ktor:ktor-server-sessions-jvm:${ktorVersion}")
    implementation("io.ktor:ktor-network-jvm:${ktorVersion}")
    implementation("io.ktor:ktor-network-tls-jvm:${ktorVersion}")
    implementation("io.ktor:ktor-network-tls-certificates-jvm:${ktorVersion}")

    //API KEY SETUP
    implementation("io.ktor:ktor-server-request-validation:${ktorVersion}")
    implementation("io.ktor:ktor-server-auth:${ktorVersion}")
//Rate Limiter
    implementation("io.ktor:ktor-server-rate-limit:${ktorVersion}")
    // Optional: Netty
    implementation("io.netty:netty-all:4.2.0.Final")


    testImplementation( "org.jetbrains.kotlin:kotlin-test-junit5:1.9.22")
    implementation("org.jetbrains.kotlin:kotlin-serialization:1.9.22")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.10.0")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.9.22")
    implementation("com.squareup.okhttp3:okhttp:5.0.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.5.1")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1")
    implementation("org.mongodb:mongodb-driver-kotlin-coroutine:5.0.0")
    implementation("org.mongodb:bson-kotlinx:5.0.0")


    implementation("io.github.oshai:kotlin-logging-jvm:7.0.3")
    implementation("ch.qos.logback:logback-classic:1.5.18")
    implementation("com.github.loki4j:loki-logback-appender:1.5.1")




    implementation("org.jetbrains.exposed:exposed-core:${exposedVersion}")
    implementation("org.jetbrains.exposed:exposed-jdbc:${exposedVersion}")
    implementation("org.jetbrains.exposed:exposed-dao:${exposedVersion}")
    implementation("org.jetbrains.exposed:exposed-json:${exposedVersion}")
    implementation("org.jetbrains.exposed:exposed-kotlin-datetime:${exposedVersion}")

    implementation("org.postgresql:postgresql:42.7.7")
}

//Allows null safety for springboot application
tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs += "-Xjsr305=strict"
    }
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
kotlin {
    jvmToolchain(21)
}

application {
    mainClass.set("MainKt")
}

